<?php
namespace Test\Functional;

use App\Database\QueryBuilder;
use App\Entity\BugReport;
use App\Helpers\DbQueryBuilderFactory;
use App\Repository\BugReportRepository;
use PHPUnit\Framework\TestCase;

class CrudTest extends TestCase
{
    /** @var BugReportRepository @repository */
    private $repository;

    /** @var QueryBuilder $queryBuilder */
    private $queryBuilder;

    private $client;

    protected function setUp()
    {
        $this->queryBuilder = DbQueryBuilderFactory::make('database', 'pdo', ['db_name' => 'bug_app_testing']);
        //$this->queryBuilder->beginTransaction();
        $this->repository = new BugReportRepository($this->queryBuilder);
        $this->client = new HttpClient();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

//    protected function tearDown()
//    {
//        $this->queryBuilder->rollback();
//        parent::tearDown();
//    }


    public function testItCanCreateReportUsingPostRequest()
    {
        $postData = $this->getPostData(['add' => true]);
        $this->client->post("http://localhost/bug_tracking_app/src/add.php", $postData);

        $result = $this->repository->findBy([
            ['report_type', '=', 'Audio Issue'],
            ['email', '=', 'xyz@abc.com'],
            ['link', '=', 'https://xyz-link.com']
        ]);

        /** @var BugReport $bugReport */
        $bugReport = $result[0] ?? [];

        self::assertInstanceOf(BugReport::class, $bugReport);
        self::assertSame('Audio Issue', $bugReport->getReportType());
        self::assertSame('https://xyz-link.com', $bugReport->getLink());
        self::assertSame('xyz@abc.com', $bugReport->getEmail());

        return $bugReport;
    }

    private function getPostData(array  $options = []): array
    {
        return array_merge([
            'report_type'   =>  'Audio Issue',
            'message'       =>  'There is an audio issue on 2.0 tutorial, please check and fix it',
            'email'         =>  'xyz@abc.com',
            'link'          =>  'https://xyz-link.com',
        ], $options);
    }
}