<?php
namespace Test\Functional;

use App\Database\QueryBuilder;
use App\Helpers\DbQueryBuilderFactory;
use App\Repository\BugReportRepository;
use PHPUnit\Framework\TestCase;

class CrudTest extends TestCase
{
    /** @var BugReportRepository @repository */
    private $repository;

    /** @var QueryBuilder $queryBuilder */
    private $queryBuilder;

    protected function setUp()
    {
        $this->queryBuilder = DbQueryBuilderFactory::make('database', 'pdo', ['db_name' => 'bug_app_testing']);
        $this->queryBuilder->beginTransaction();
        $this->repository = new BugReportRepository($this->queryBuilder);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        $this->queryBuilder->rollback();
        parent::tearDown();
    }


    
}